In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
# acessar a página de notícias da Anvisa
url = "https://www.gov.br/anvisa/pt-br/assuntos/noticias-anvisa"

html = requests.get(url).text
soup = BeautifulSoup(html, "html.parser")

dados = []

In [3]:
# iterar sobre cada notícia encontrada na página
for noticia in soup.find_all("li"):

    titulo_tag = noticia.find("h2", class_="titulo")
    data_tag = noticia.find("span", class_="data")

    if titulo_tag:

        link_tag = titulo_tag.find("a")

        dados.append({
            "titulo": link_tag.get_text(strip=True),
            "link": link_tag["href"],
            "data": data_tag.get_text(strip=True) if data_tag else None
        })


#salvar em um dataframe do pandas
df = pd.DataFrame(dados)

In [4]:
df

,titulo,link,data
0,"Vigipós 25 anos - Passado, presente e futuro d...",https://www.gov.br/anvisa/pt-br/assuntos/notic...,28/05/2026
1,Anvisa proíbe venda de suplementos alimentares...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,28/05/2026
2,Anvisa proíbe creme redutor de medidas por fal...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,28/05/2026
3,Anvisa determina recolhimento de coco ralado d...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,28/05/2026
4,Anvisa aprimora transparência das filas de aná...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,28/05/2026
5,Anvisa institui Câmara Técnica de Biovigilância,https://www.gov.br/anvisa/pt-br/assuntos/notic...,27/05/2026
6,Anvisa fará consulta pública para criação do S...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,27/05/2026
7,27 anos dos medicamentos genéricos no Brasil,https://www.gov.br/anvisa/pt-br/assuntos/notic...,26/05/2026
8,Anvisa e Mapa lançam plataforma unificada para...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,26/05/2026
9,Anvisa aprova ampliação de uso de medicamento ...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,26/05/2026
10,Acompanhe a 9ª Reunião Ordinária Pública da Di...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,26/05/2026
11,Anvisa aprova primeira caneta de semaglutida s...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,26/05/2026
12,Webinar trará esclarecimentos sobre o Projeto...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,25/05/2026
13,Comissão de Ética da Anvisa se solidariza com ...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,25/05/2026
14,Boletim de maio destaca ações nacionais voltad...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,25/05/2026
15,Anvisa autoriza novo medicamento para enxaqueca,https://www.gov.br/anvisa/pt-br/assuntos/notic...,25/05/2026
16,Novo registro de genérico amplia acesso ao tra...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,25/05/2026
17,Evento discutirá oportunidades de colaboração ...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,25/05/2026
18,Anvisa aprova novo medicamento para doença de ...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,25/05/2026
19,Anvisa proíbe produtos da marca Now Foods,https://www.gov.br/anvisa/pt-br/assuntos/notic...,25/05/2026
20,Anvisa e vigilâncias do DF e do Tocantins inte...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,22/05/2026
21,Anvisa e Unesco selecionam consultor técnico p...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,22/05/2026
22,Anvisa divulga programação I Encontro Nacional...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,22/05/2026
23,Acompanhe o I Seminário de Medicinas Tradicion...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,22/05/2026
24,Anvisa celebra 25 anos da vigilância pós-mercado,https://www.gov.br/anvisa/pt-br/assuntos/notic...,21/05/2026
25,Dia Mundial de Proteção ao Aleitamento é marca...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,21/05/2026
26,Anvisa estabelece classificação toxicológica e...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,21/05/2026
27,Publicada nova atualização da Lista de Medicam...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,21/05/2026
28,SNCR: o que muda para farmácias e drogarias co...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,21/05/2026
29,Anvisa determina interdição cautelar de repele...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,20/05/2026

In [5]:
#usar o link de cada notícia para acessar o conteúdo completo e extrair o texto
textos = []

for link in df["link"]:

    html = requests.get(link).text
    soup = BeautifulSoup(html, "html.parser")

    corpo = soup.select_one("#content-core")

    if corpo:
        paragrafos = corpo.find_all("p")
        texto = " ".join(p.get_text(strip=True) for p in paragrafos)
    else:
        texto = None

    textos.append(texto)

df["texto"] = textos

#salvar em um arquivo CSV
#df.to_csv("noticias_anvisa_com_texto.csv", index=False, encoding="utf-8-sig")

In [7]:
df.to_csv("noticias_anvisa_com_texto.csv", index=False, encoding="utf-8-sig")

In [6]:
df.head()

,titulo,link,data,texto
0,"Vigipós 25 anos - Passado, presente e futuro d...",https://www.gov.br/anvisa/pt-br/assuntos/notic...,28/05/2026,"AVigipós, como é conhecida, é o trabalho de ol..."
1,Anvisa proíbe venda de suplementos alimentares...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,28/05/2026,A Agência Nacional de Vigilância Sanitária (An...
2,Anvisa proíbe creme redutor de medidas por fal...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,28/05/2026,Uma medida publicada pela Agência Nacional de ...
3,Anvisa determina recolhimento de coco ralado d...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,28/05/2026,A Agência Nacional de Vigilância Sanitária (An...
4,Anvisa aprimora transparência das filas de aná...,https://www.gov.br/anvisa/pt-br/assuntos/notic...,28/05/2026,A Agência Nacional de Vigilância Sanitária (An...